### ISSUE TITLE
Licensing and use

### ISSUE THREAD

**Issue by sebasarango1180** [AaronDavidNewman/Smoosic#42]
Hey Aaron,

I'm currently using the Smoosic API as a component for my MSc project, and now this university wants to consolidate my project as an (possibly licensed) academic product. I haven't been able to see what the Smoosic's licensing model looks like and to what extent it can be used for other projects. Could you please further clarify on that?

Thanks!

**Comment by AaronDavidNewman** [comment]
That's so neat!  I'm eager to see your project.

The license will be similar to the VexFlow license, with my name in the
place of Mohit's.  (also, as a  derivative work, it is probably also bound
by vexflow license, NAL etc.).  Basically, you can use it for any purpose,
as long as you acknowledge the copyright owner (me).  Since you are not the
first person to ask, I will make an effort to add it to the repo and
comments, I'd better get on this before AWS offers it as their thing.

https://github.com/0xfe/vexflow/blob/master/LICENSE

**Comment by sebasarango1180** [comment]
Wow, thanks!
I'll be looking forward to it, and of course, I'll let you know how my project goes on 👍
